/// <reference types="vitest" />
import react from '@vitejs/plugin-react-swc';
import { defineConfig } from 'vite';
import tsconfigPaths from 'vite-tsconfig-paths';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), tsconfigPaths()],
  base: process.env.NODE_ENV === 'production' ? '/guthib/' : '/',
  test: {
    globals: true,
    environment: 'jsdom',
    coverage: {
      reporter: ['html-spa'],
      include: ['src/**/*.{jsx,tsx}', 'src/**/*.{js,ts}'],
      exclude: [
        'src/**/*.d.ts',
        // Ignore the index.ts file since we don't want to hit github api and got a rate limit
        'src/utils/github/index.ts',
        // Ignore the components/ui since it was generated by Chakra UI
        'src/components/ui/**/*.{jsx,tsx}',
      ],
    },
    include: ['src/**/*.{test,spec}.{js,ts}', 'src/**/*.{test,spec}.{jsx,tsx}'],
  },
});
